### ISSUE TITLE
Conseil should accept supplementary metadata from a file

### ISSUE THREAD

**Issue by vishakh** [Cryptonomic/Conseil#316]
Conseil should accept supplementary content in files for its metadata routes, e.g. `displayName` for the `attributes` routes. The metadata can be maintained in a file called `attributes.xml` which could have the following format:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<platforms>
	<platform name="tezos" visible="true" displayName="Tezos" description="The Tezos blockchain">
		<networks>
			<network name="alphanet" visible="true" displayName="Alphanet" description="Official Tezos testnet">
				<entities>
					<entity name="blocks" visible="true" displayName="Blocks" description="Blocks">
						<attributes>
							<attribute name="level" visible="true" displayName="Block level" description="Height of block in blockchain" />
						</attributes>
					</entity>
				</entities>
			</network>
		</networks>
	</platform>
</platforms>
```

Platforms, networks, entities and attributes should not be returned by the metadata routes **unless** they appear in this file and their corresponding `visible` flag is set to `true`. The schema returned by the metadata routes should be enhanced to accept all the new information in the XML file. 

An XML schema should be created for the above content and any provided file should be validated upfront for errors.

Conseil should also accept override metadata files as command-line parameters.

**Comment by ivanopagano** [comment]
I'm still a bit short of grasping where/when these files are read and what should they do.
Is this supposed to only show a nested structure similar to that of the platform endpoints, with extra detail on the actual attributes? Or should it additionally contain data as content in the tags?

I'm trying to understand if a YAML-like format would serve the same purpose or not

**Comment by piotrkosecki** [comment]
From what I understood, we would need to change model so it had additional fields described here, and during startup load this file and do simple `getOrElse` on each field if column/table has `visible` attribute set to `true`. This would need to be integrated with caching which I've implemented recently. Did I understand it correctly @vishakh?

**Comment by ivanopagano** [comment]
Thus I'm lead to assume that Yaml could do as well? With proper schema validation

**Comment by dorians** [comment]
Yeah, that one should work: 
```
platforms:
  - name: tezos
    displayName: Tezos
    visible: true
    networks:
      - name: alphanet
        displayName: Alphanet
        visible: true
        entities:
          - name: blocks
            displayName: Blocks
            visible: true
            attributes:
              - displayName: "Block level"
                name: level
                visible: true
```
